language: c
os: linux
sudo: false
compiler: gcc
dist: xenial
branches:
  only:
  - master
  - develop

before_script: 
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then
		cd Make/gcc
	fi

script: 
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then
		make
	fi
