language: c

branches:
  only:
  - master
  - develop

matrix:
  include:
    - os: linux
      sudo: false
      compiler: gcc
      dist: trusty
      before_script: 
        cd Make/gcc
      script: 
        make
      after_success:
          - cd Make/gcc
          - ./update-version.sh 
          - git config --global user.email "opensea-build@seagate.com" 
          - git config --global user.name "Travis CI"
          - git add -u
          - git commit -m "[skip travis] version changed" 
          - git push

    - os: linux
      sudo: false
      compiler: clang
      dist: trusty
      before_script: 
        cd Make/gcc
      script: 
        make        
    - os: windows
      env:
        - MSBUILD_PATH="c:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin"
      before_script: 
        cd "Make\VS.2017\opensea-common"
      script: 
        - export PATH=$MSBUILD_PATH:$PATH 
        - MSBuild.exe //p:Configuration=Release //p:Platform=x64

